create or replace function public.forum_is_admin()
returns boolean
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) in ('koki142@gmail.com');
$$;

create table if not exists public.forum_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_profiles_display_name_length check (
    char_length(trim(display_name)) between 2 and 80
  ),
  constraint forum_profiles_bio_length check (
    bio is null or char_length(bio) <= 280
  )
);

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  color text not null default '#d93e3e',
  author_id uuid references auth.users(id) on delete set null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint forum_categories_slug_format check (slug ~ '^[a-z0-9-]+$')
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.forum_categories(id) on delete cascade,
  slug text not null,
  title text not null,
  excerpt text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar_url text,
  reply_count integer not null default 0,
  post_count integer not null default 0,
  is_locked boolean not null default false,
  is_pinned boolean not null default false,
  hidden_at timestamptz,
  hidden_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_post_at timestamptz not null default now(),
  constraint forum_topics_slug_format check (slug ~ '^[a-z0-9-]+$'),
  constraint forum_topics_title_length check (
    char_length(trim(title)) between 4 and 140
  ),
  constraint forum_topics_excerpt_length check (
    excerpt is null or char_length(excerpt) <= 220
  ),
  unique (category_id, slug)
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  parent_id bigint references public.forum_posts(id) on delete set null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar_url text,
  content text not null,
  hidden_at timestamptz,
  hidden_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_posts_content_length check (
    char_length(trim(content)) between 2 and 6000
  )
);

create table if not exists public.forum_post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  constraint forum_post_reports_reason_length check (
    reason is null or char_length(reason) <= 500
  ),
  unique (post_id, reporter_id)
);

create or replace function public.set_forum_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_forum_profiles_updated_at on public.forum_profiles;
create trigger set_forum_profiles_updated_at
before update on public.forum_profiles
for each row
execute function public.set_forum_updated_at();

drop trigger if exists set_forum_topics_updated_at on public.forum_topics;
create trigger set_forum_topics_updated_at
before update on public.forum_topics
for each row
execute function public.set_forum_updated_at();

drop trigger if exists set_forum_posts_updated_at on public.forum_posts;
create trigger set_forum_posts_updated_at
before update on public.forum_posts
for each row
execute function public.set_forum_updated_at();

create or replace function public.guard_forum_post_author_update()
returns trigger
language plpgsql
as $$
begin
  if public.forum_is_admin() then
    return new;
  end if;

  if new.id is distinct from old.id
    or new.topic_id is distinct from old.topic_id
    or new.parent_id is distinct from old.parent_id
    or new.author_id is distinct from old.author_id
    or new.author_name is distinct from old.author_name
    or new.author_avatar_url is distinct from old.author_avatar_url
    or new.hidden_at is distinct from old.hidden_at
    or new.hidden_by is distinct from old.hidden_by
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Only forum admins can moderate forum posts.';
  end if;

  return new;
end;
$$;

drop trigger if exists guard_forum_posts_author_update on public.forum_posts;
create trigger guard_forum_posts_author_update
before update on public.forum_posts
for each row
execute function public.guard_forum_post_author_update();

create or replace function public.refresh_forum_topic_stats(target_topic_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  visible_post_count integer;
  newest_post_at timestamptz;
begin
  select count(*), max(created_at)
  into visible_post_count, newest_post_at
  from public.forum_posts
  where topic_id = target_topic_id
    and hidden_at is null;

  update public.forum_topics
  set
    post_count = coalesce(visible_post_count, 0),
    reply_count = greatest(coalesce(visible_post_count, 0) - 1, 0),
    last_post_at = coalesce(newest_post_at, created_at)
  where id = target_topic_id;
end;
$$;

create or replace function public.sync_forum_topic_stats()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_forum_topic_stats(old.topic_id);
    return old;
  end if;

  perform public.refresh_forum_topic_stats(new.topic_id);
  return new;
end;
$$;

drop trigger if exists sync_forum_topic_stats_insert on public.forum_posts;
create trigger sync_forum_topic_stats_insert
after insert on public.forum_posts
for each row
execute function public.sync_forum_topic_stats();

drop trigger if exists sync_forum_topic_stats_update on public.forum_posts;
create trigger sync_forum_topic_stats_update
after update of hidden_at on public.forum_posts
for each row
execute function public.sync_forum_topic_stats();

drop trigger if exists sync_forum_topic_stats_delete on public.forum_posts;
create trigger sync_forum_topic_stats_delete
after delete on public.forum_posts
for each row
execute function public.sync_forum_topic_stats();

alter table public.forum_profiles enable row level security;
alter table public.forum_categories enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;
alter table public.forum_post_reports enable row level security;

alter table public.forum_categories
add column if not exists author_id uuid references auth.users(id) on delete set null;

drop policy if exists "Forum profiles are public" on public.forum_profiles;
create policy "Forum profiles are public"
on public.forum_profiles
for select
to anon, authenticated
using (true);

drop policy if exists "Users insert their forum profile" on public.forum_profiles;
create policy "Users insert their forum profile"
on public.forum_profiles
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users update their forum profile" on public.forum_profiles;
create policy "Users update their forum profile"
on public.forum_profiles
for update
to authenticated
using (user_id = auth.uid() or public.forum_is_admin())
with check (user_id = auth.uid() or public.forum_is_admin());

drop policy if exists "Active forum categories are public" on public.forum_categories;
create policy "Active forum categories are public"
on public.forum_categories
for select
to anon, authenticated
using (is_active or public.forum_is_admin());

drop policy if exists "Authenticated users create forum categories" on public.forum_categories;
drop policy if exists "Admins create forum categories" on public.forum_categories;
drop policy if exists "Admins manage forum categories" on public.forum_categories;
drop policy if exists "Admins insert forum categories" on public.forum_categories;
drop policy if exists "Admins update forum categories" on public.forum_categories;
drop policy if exists "Admins delete forum categories" on public.forum_categories;
drop policy if exists "Users insert forum categories" on public.forum_categories;
drop policy if exists "Owners and admins update forum categories" on public.forum_categories;
drop policy if exists "Owners and admins delete forum categories" on public.forum_categories;

create policy "Users insert forum categories"
on public.forum_categories
for insert
to authenticated
with check (
  author_id = auth.uid()
  and sort_order between 0 and 10000
  and char_length(trim(title)) between 2 and 60
  and (description is null or char_length(description) <= 180)
);

create policy "Owners and admins update forum categories"
on public.forum_categories
for update
to authenticated
using (author_id = auth.uid() or public.forum_is_admin())
with check (
  (author_id = auth.uid() or public.forum_is_admin())
  and sort_order between 0 and 10000
  and char_length(trim(title)) between 2 and 60
  and (description is null or char_length(description) <= 180)
);

create policy "Owners and admins delete forum categories"
on public.forum_categories
for delete
to authenticated
using (author_id = auth.uid() or public.forum_is_admin());

notify pgrst, 'reload schema';

drop policy if exists "Visible forum topics are public" on public.forum_topics;
create policy "Visible forum topics are public"
on public.forum_topics
for select
to anon, authenticated
using (
  hidden_at is null
  or author_id = auth.uid()
  or public.forum_is_admin()
);

drop policy if exists "Authenticated users create forum topics" on public.forum_topics;
create policy "Authenticated users create forum topics"
on public.forum_topics
for insert
to authenticated
with check (
  author_id = auth.uid()
  and hidden_at is null
  and exists (
    select 1
    from public.forum_categories
    where forum_categories.id = category_id
      and forum_categories.is_active
  )
);

drop policy if exists "Admins moderate forum topics" on public.forum_topics;
create policy "Admins moderate forum topics"
on public.forum_topics
for update
to authenticated
using (public.forum_is_admin())
with check (public.forum_is_admin());

drop policy if exists "Authors and admins delete forum topics" on public.forum_topics;
create policy "Authors and admins delete forum topics"
on public.forum_topics
for delete
to authenticated
using (author_id = auth.uid() or public.forum_is_admin());

drop policy if exists "Visible forum posts are public" on public.forum_posts;
create policy "Visible forum posts are public"
on public.forum_posts
for select
to anon, authenticated
using (
  hidden_at is null
  or author_id = auth.uid()
  or public.forum_is_admin()
);

drop policy if exists "Authenticated users create forum posts" on public.forum_posts;
create policy "Authenticated users create forum posts"
on public.forum_posts
for insert
to authenticated
with check (
  author_id = auth.uid()
  and hidden_at is null
  and exists (
    select 1
    from public.forum_topics
    where forum_topics.id = topic_id
      and forum_topics.hidden_at is null
      and (not forum_topics.is_locked or public.forum_is_admin())
  )
);

drop policy if exists "Authors and admins update forum posts" on public.forum_posts;
create policy "Authors and admins update forum posts"
on public.forum_posts
for update
to authenticated
using (author_id = auth.uid() or public.forum_is_admin())
with check (author_id = auth.uid() or public.forum_is_admin());

drop policy if exists "Admins delete forum posts" on public.forum_posts;
drop policy if exists "Authors and admins delete forum posts" on public.forum_posts;
create policy "Authors and admins delete forum posts"
on public.forum_posts
for delete
to authenticated
using (author_id = auth.uid() or public.forum_is_admin());

drop policy if exists "Users and admins read forum reports" on public.forum_post_reports;
create policy "Users and admins read forum reports"
on public.forum_post_reports
for select
to authenticated
using (reporter_id = auth.uid() or public.forum_is_admin());

drop policy if exists "Authenticated users create forum reports" on public.forum_post_reports;
create policy "Authenticated users create forum reports"
on public.forum_post_reports
for insert
to authenticated
with check (reporter_id = auth.uid());

drop policy if exists "Admins update forum reports" on public.forum_post_reports;
create policy "Admins update forum reports"
on public.forum_post_reports
for update
to authenticated
using (public.forum_is_admin())
with check (public.forum_is_admin());

create index if not exists forum_categories_sort_order_idx
on public.forum_categories (sort_order, title);

create index if not exists forum_topics_category_last_post_idx
on public.forum_topics (category_id, is_pinned desc, last_post_at desc);

create index if not exists forum_topics_author_idx
on public.forum_topics (author_id, created_at desc);

create index if not exists forum_posts_topic_created_idx
on public.forum_posts (topic_id, created_at asc);

create index if not exists forum_posts_parent_idx
on public.forum_posts (parent_id);

create index if not exists forum_post_reports_post_idx
on public.forum_post_reports (post_id, created_at desc);

insert into public.forum_categories (slug, title, description, color, sort_order)
values
  (
    'japon',
    'Japón',
    'Actualidad, vida diaria y rarezas japonesas para comentar con calma.',
    '#d93e3e',
    10
  ),
  (
    'off-topic',
    'Off-topic',
    'La barra libre: preguntas, memes, recomendaciones y divagues varios.',
    '#8f6a2a',
    20
  ),
  (
    'ideas',
    'Ideas para noticias',
    'Pistas, enlaces y ocurrencias para futuras piezas de Ohayers.',
    '#2f6f5f',
    30
  )
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  color = excluded.color,
  sort_order = excluded.sort_order,
  is_active = true;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'forum-images',
  'forum-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Forum images are public" on storage.objects;
drop policy if exists "Users upload forum images" on storage.objects;
drop policy if exists "Users update own forum images" on storage.objects;
drop policy if exists "Users delete own forum images" on storage.objects;

create policy "Forum images are public"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'forum-images');

create policy "Users upload forum images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'forum-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users update own forum images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'forum-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.forum_is_admin()
  )
)
with check (
  bucket_id = 'forum-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.forum_is_admin()
  )
);

create policy "Users delete own forum images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'forum-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.forum_is_admin()
  )
);
