create or replace function public.forum_is_admin()
returns boolean
language sql
stable
as $$
  select lower(coalesce(
    nullif(auth.jwt() ->> 'email', ''),
    nullif(auth.jwt() #>> '{user_metadata,email}', ''),
    nullif(auth.jwt() #>> '{app_metadata,email}', ''),
    ''
  )) in ('koki142@gmail.com');
$$;

create table if not exists public.forum_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_profiles_display_name_length check (
    char_length(trim(display_name)) between 2 and 80
  ),
  constraint forum_profiles_bio_length check (
    bio is null or char_length(bio) <= 280
  )
);

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  color text not null default '#d93e3e',
  author_id uuid references auth.users(id) on delete set null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint forum_categories_slug_format check (slug ~ '^[a-z0-9-]+$')
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.forum_categories(id) on delete cascade,
  slug text not null,
  title text not null,
  excerpt text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar_url text,
  event_start_date date,
  event_end_date date,
  event_location text,
  event_zone text,
  reply_count integer not null default 0,
  post_count integer not null default 0,
  is_locked boolean not null default false,
  is_pinned boolean not null default false,
  hidden_at timestamptz,
  hidden_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_post_at timestamptz not null default now(),
  constraint forum_topics_slug_format check (slug ~ '^[a-z0-9-]+$'),
  constraint forum_topics_title_length check (
    char_length(trim(title)) between 4 and 140
  ),
  constraint forum_topics_excerpt_length check (
    excerpt is null or char_length(excerpt) <= 220
  ),
  constraint forum_topics_event_location_length check (
    event_location is null
    or char_length(trim(event_location)) between 1 and 120
  ),
  constraint forum_topics_event_zone_value check (
    event_zone is null
    or event_zone in (
      'Hokkaido',
      'Tohoku',
      'Kanto',
      'Chubu',
      'Kansai',
      'Chugoku',
      'Shikoku',
      'Kyushu',
      'Okinawa'
    )
  ),
  constraint forum_topics_event_dates_order check (
    event_end_date is null
    or (
      event_start_date is not null
      and event_end_date >= event_start_date
    )
  ),
  unique (category_id, slug)
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  parent_id bigint references public.forum_posts(id) on delete set null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar_url text,
  content text not null,
  hidden_at timestamptz,
  hidden_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forum_posts_content_length check (
    char_length(trim(content)) between 2 and 6000
  )
);

create table if not exists public.forum_post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  constraint forum_post_reports_reason_length check (
    reason is null or char_length(reason) <= 500
  ),
  unique (post_id, reporter_id)
);
